version: '3.7'
services:

  web:
    build: .
    image: uzman
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/Hotel
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - migrate
      - migration

  migrate:
    image: uzman
    command: python manage.py migrate --noinput
    volumes:
      - .:/usr/src/Hotel
    env_file:
      - ./.env.dev
    depends_on:
      - db

  migration:
    image: uzman
    command: python manage.py makemigrations --noinput
    volumes:
      - .:/usr/src/Hotel
    env_file:
      - ./.env.dev
    depends_on:
      - db


  db:
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=apple123
      - POSTGRES_DB=hotel
    expose:
      - 5432
    ports:
      - 0.0.0.0:5432:5432

volumes:
  postgres_data: