# Generated by Django 2.2.12 on 2020-12-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date_start',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.IntegerField(db_index=True),
        ),
    ]
